export const studioCopy = {
  en: {
    createTitle: 'Create with AI',
    createDescription: 'Describe a presentation, then refine it in Deckspring.',
    localWorkspace: 'Local workspace',
    promptLabel: 'What should this presentation cover?',
    promptPlaceholder:
      'A six-page briefing on our Q4 product roadmap. Cover priorities, tradeoffs, milestones, and decisions needed.',
    try: 'Try',
    productLaunch: 'Product launch',
    investorUpdate: 'Investor update',
    productPrompt:
      'A concise product launch brief for a new team collaboration app. Cover the user problem, product idea, three key features, launch plan, and next steps.',
    investorPrompt:
      'An investor update for a growing B2B software company. Summarize traction, customer insight, product progress, risks, and next quarter priorities without inventing numbers.',
    pages: 'Pages',
    pageUnit: 'pages',
    palette: 'Deck palette',
    cobalt: 'Cobalt',
    citrus: 'Citrus',
    evergreen: 'Evergreen',
    midnight: 'Midnight',
    outputLanguage: 'Output language',
    english: 'English',
    arabic: 'العربية',
    generating: 'Generating…',
    generate: 'Generate deck',
    models: 'Models',
    addModel: 'Add model',
    loadingModels: 'Loading models…',
    noModels: 'Add an OpenAI-compatible model to start generating.',
    ready: 'Ready',
    needsKey: 'Needs key',
    edit: 'Edit',
    keyMemory: 'API keys stay in memory until you close the local app.',
    editModel: 'Edit model',
    addAModel: 'Add a model',
    connectionDescription: 'Connect an OpenAI-compatible chat completions endpoint.',
    connectionName: 'Connection name',
    baseUrl: 'Base URL',
    modelName: 'Model name',
    apiKey: 'API key',
    keyPlaceholder: 'Enter a key, if required',
    keepKeyPlaceholder: 'Leave blank to keep this session key',
    localDetails:
      'Connection details are saved locally. The API key stays in memory for this session.',
    delete: 'Delete',
    testConnection: 'Test connection',
    saving: 'Saving…',
    saveModel: 'Save model',
    deleteConfirm: 'Delete this model connection?',
    modelSaved: 'Model saved.',
    modelDeleted: 'Model deleted.',
    contacting: 'Contacting the model…',
    connectionWorks: 'Connection works.',
    writingDeck: 'Writing the deck. This can take a minute.',
    loadModelsError: 'Could not load models',
    generationFailed: 'Generation failed.',
    resumeError: 'Could not resume generation',
    chooseModel: 'Add and choose a model first.',
    enterKey: 'Enter this model’s API key to continue.',
    reviewWithModel: 'Apply with model',
    commentHelp: 'Sends each comment and nearby slide source to this model for a proposed edit.',
    saveBeforeReview: 'Save your current slide edits before reviewing comments.',
    reviewing: 'Reviewing comments…',
    reviewAiEdits: 'Review AI edits',
    addModelInSlides: 'Add a model in Slides',
    toApplyComments: 'to apply comments here.',
    reviewTitle: 'Review comment edits',
    reviewDescription:
      'Select the source changes to write to this slide. Unselected comments stay pending.',
    before: 'Before',
    after: 'After',
    skipped: 'Skipped',
    noChanges: 'The model proposed no changes.',
    cancel: 'Cancel',
    apply: 'Apply',
    change: 'change',
    changes: 'changes',
    comment: 'comment',
    comments: 'comments',
    applied: 'applied.',
    loadModels: 'Could not load models.',
    reviewError: 'Could not review comments.',
    applyError: 'Could not apply comments.',
  },
  ar: {
    createTitle: 'إنشاء بالذكاء الاصطناعي',
    createDescription: 'صِف عرضك التقديمي، ثم حسّنه في Deckspring.',
    localWorkspace: 'مساحة عمل محلية',
    promptLabel: 'ما موضوع هذا العرض؟',
    promptPlaceholder:
      'عرض موجز من ست صفحات عن خطة المنتج للربع القادم، يشمل الأولويات والمراحل والقرارات المطلوبة.',
    try: 'جرّب',
    productLaunch: 'إطلاق منتج',
    investorUpdate: 'تحديث للمستثمرين',
    productPrompt:
      'عرض موجز لإطلاق تطبيق جديد لتعاون الفرق. اشرح مشكلة المستخدم، وفكرة المنتج، وثلاث ميزات رئيسية، وخطة الإطلاق، والخطوات التالية.',
    investorPrompt:
      'تحديث للمستثمرين عن شركة برمجيات نامية. لخّص النمو، وآراء العملاء، وتطور المنتج، والمخاطر، وأولويات الربع القادم دون اختلاق أرقام.',
    pages: 'الصفحات',
    pageUnit: 'صفحات',
    palette: 'ألوان العرض',
    cobalt: 'كوبالت',
    citrus: 'حمضيات',
    evergreen: 'أخضر',
    midnight: 'ليلي',
    outputLanguage: 'لغة العرض',
    english: 'English',
    arabic: 'العربية',
    generating: 'جارٍ الإنشاء…',
    generate: 'إنشاء العرض',
    models: 'النماذج',
    addModel: 'إضافة نموذج',
    loadingModels: 'جارٍ تحميل النماذج…',
    noModels: 'أضف نموذجًا متوافقًا مع OpenAI لبدء إنشاء العروض.',
    ready: 'جاهز',
    needsKey: 'يحتاج مفتاحًا',
    edit: 'تحرير',
    keyMemory: 'تبقى مفاتيح API في الذاكرة حتى تغلق التطبيق المحلي.',
    editModel: 'تحرير النموذج',
    addAModel: 'إضافة نموذج',
    connectionDescription: 'اربط نقطة اتصال متوافقة مع واجهة OpenAI للدردشة.',
    connectionName: 'اسم الاتصال',
    baseUrl: 'الرابط الأساسي',
    modelName: 'اسم النموذج',
    apiKey: 'مفتاح API',
    keyPlaceholder: 'أدخل المفتاح إذا لزم الأمر',
    keepKeyPlaceholder: 'اتركه فارغًا للاحتفاظ بمفتاح هذه الجلسة',
    localDetails: 'تُحفظ تفاصيل الاتصال محليًا. يبقى مفتاح API في ذاكرة هذه الجلسة.',
    delete: 'حذف',
    testConnection: 'اختبار الاتصال',
    saving: 'جارٍ الحفظ…',
    saveModel: 'حفظ النموذج',
    deleteConfirm: 'هل تريد حذف اتصال هذا النموذج؟',
    modelSaved: 'حُفظ النموذج.',
    modelDeleted: 'حُذف النموذج.',
    contacting: 'جارٍ الاتصال بالنموذج…',
    connectionWorks: 'الاتصال يعمل.',
    writingDeck: 'جارٍ كتابة العرض. قد يستغرق الأمر دقيقة.',
    loadModelsError: 'تعذّر تحميل النماذج',
    generationFailed: 'فشل إنشاء العرض.',
    resumeError: 'تعذّر استئناف الإنشاء',
    chooseModel: 'أضف نموذجًا واختره أولًا.',
    enterKey: 'أدخل مفتاح API لهذا النموذج للمتابعة.',
    reviewWithModel: 'تطبيق باستخدام النموذج',
    commentHelp: 'يُرسل كل تعليق وجزءًا من مصدر الشريحة إلى النموذج لاقتراح تعديل.',
    saveBeforeReview: 'احفظ تعديلات الشريحة الحالية قبل مراجعة التعليقات.',
    reviewing: 'جارٍ مراجعة التعليقات…',
    reviewAiEdits: 'مراجعة تعديلات AI',
    addModelInSlides: 'أضف نموذجًا في الشرائح',
    toApplyComments: 'لتطبيق التعليقات هنا.',
    reviewTitle: 'مراجعة تعديلات التعليقات',
    reviewDescription:
      'اختر تغييرات المصدر التي تريد كتابتها إلى الشريحة. تبقى التعليقات غير المحددة معلّقة.',
    before: 'قبل',
    after: 'بعد',
    skipped: 'تم تجاوز',
    noChanges: 'لم يقترح النموذج أي تغييرات.',
    cancel: 'إلغاء',
    apply: 'تطبيق',
    change: 'تغيير',
    changes: 'تغييرات',
    comment: 'تعليق',
    comments: 'تعليقات',
    applied: 'تم تطبيقها.',
    loadModels: 'تعذّر تحميل النماذج.',
    reviewError: 'تعذّرت مراجعة التعليقات.',
    applyError: 'تعذّر تطبيق التعليقات.',
  },
} as const;
